### ISSUE TITLE
Cannot send transactions with VIem adapter: Cannot use 'in' operator to search for 'rpcUrls' in undefined

### ISSUE THREAD

**Issue by jaxernst** [thirdweb-dev/js#2661] opened 2024-04-03 00:12 UTC
I'm attempting to use an embedded wallet in my app with the Viem adapter, but I've been unable to get transactions to send. Transactions are failing with the following error:

```
TransactionExecutionError: An unknown RPC error occurred.

Request Arguments:
  from:   0x0e27Af5cF96515759ecF27FC3247556f450232DB
  to:     0x0000000000000000000000000000000000000000
  value:  0 ETH

Details: Cannot use 'in' operator to search for 'rpcUrls' in undefined
Version: viem@2.9.6
    at getTransactionError (chunk-RD27M5LS.js?v=f641f710:1334:10)
    at sendTransaction (chunk-RD27M5LS.js?v=f641f710:1416:11)
```

I've tried this several different inputs for 'defineChain', both with ViemChain types and chain ids, none of which seem to work.

This minimal reproduction is causing the error for me when building with Vite for use in a Sveltekit app with thirdweb@5.1.0, and viem@2.9.6

```typescript
import { createThirdwebClient, defineChain } from "thirdweb";
import { embeddedWallet } from "thirdweb/wallets/embedded";
import { viemAdapter } from "thirdweb/adapters/viem";

const tw = createThirdwebClient({
  clientId: PUBLIC_THIRDWEB_CLIENT_ID,
});

const twWallet = embeddedWallet();

const chain = defineChain(1);

const account = await twWallet.connect({
  client: tw,
  strategy: "google",
});

const walletClient = viemAdapter.walletClient.toViem({
  client: tw,
  account,
  chain,
}) as Wallet;

await walletClient.sendTransaction({
  to: zeroAddress,
  value: BigInt(0),
});

```

**Comment by jnsdls** [comment] 2024-04-03 00:18
> and viem@5.9.6

I assume it's `2.9.6` :)

I'll take a look at this and see if I can reproduce it. Thank you for reporting this!

**Comment by jnsdls** [comment] 2024-04-03 00:21
We should be able to add a test-case for this to reproduce it, fix it and make sure it does not happen again.

**Comment by jnsdls** [comment] 2024-04-03 00:21
likely that the issue is happening in the viem adapter code-path, somewhere [here](https://github.com/thirdweb-dev/js/blob/main/packages/thirdweb/src/adapters/viem.ts#L173)

**Comment by jnsdls** [comment] 2024-04-03 01:34
hey there @jaxernst could you try with this dev build and see if it fixes your issue?

`thirdweb@0.0.0-dev-c5bc0f5be2ba8d7f679627f5c001e32e8122b682-20240403013049`

I was able to reproduce the error and added a test in #2662, but would love if you could confirm it works with this version, I'll then cut a new stable release tonight

**Comment by jnsdls** [comment] 2024-04-03 02:42
keeping open to wait for confirmation of fix using the change

**Comment by jaxernst** [comment] 2024-04-03 05:08
Just tested, all working for me now! Thank you

**Comment by jnsdls** [comment] 2024-04-03 05:57
Great, closing. We'll ship the release in the morning!

**Closed** 2024-04-03 05:57 UTC
Labels: bug
